---
language: python

python:
  - 3.7

install:
  - pip install mypy
  - git clone https://github.com/Shougo/denite.nvim /tmp/denite.nvim

script:
  - SRC=$(find . -name '*.py' | perl -pe 's,^\./,,')
  - |-
    RESULT=$(
      for i in $SRC; do
        export MYPYPATH=/tmp/denite.nvim/rplugin/python3:rplugin/python3
        mypy --strict $i | grep "^$i" | tee /dev/tty
      done
    )
  - |-
    if [[ -n $RESULT ]]; then
      exit 1
    fi

notifications:
  slack:
    rooms:
      secure: "xDwxiV83BqN4rAQIy0VoR/ojHb7J2vzH/yyGJiE1kQiVEQtf/UgFQZm8ZtYe09xr\
               RZfTf7Q8v8b7pBpaeL/OK6/hsRsHyos4/dGZmz2wms4wLkLUoh33vSNRtRqW6iXq\
               6gdyOUWenHNkQwvEbq/Tj74EEuVQMmhVLzf8nuGYhypunlYPZ6kml5Cljnudoyt6\
               rN+8LmpvEUncl7s49EX1p/GN/JimVnVhJRymwwOP6lyt+FOSYlxL2uKI36SjR2qP\
               eYA3Zo50e28/afHcxd1aq9fInk2+hXnInl/kyBVv3SHRaxoiCpQShervbSYQ/Ksq\
               jdv6OIlI3a7krzQ4w9pd3C8Z0d2uDIu6LK0dx8D8lN4SUfTKIzyfE1lelnExz5DW\
               BbrdjQJxThXsqsLwXHm47rIqGqB5+lz4zb4x7PWP73C3ljbDlPUrhl0evrGrxyX5\
               mxVQWjO69+97W2w9KrMyJ6PQVNvsteHmiUjJcMIQHpwo7P5cLPs7BOvunhGLT+rt\
               ya2UIyKXB8vSYy2O1g+qdJOPJXZgJO3k16v8Un1yjdU6bZeA7F3QVankKB3I/yed\
               3jBpudoZZry9SPB9fAx66D2zmsBpsG5XbWocXTMGFRtnES5B4JSCw476HFGyGI8h\
               qZ6hY1LqfRD5YFDCFM9baetcyHybYEV3kh+kRjOMAEw="
    on_success: never
